#include "Skriware_Variables.h"
#include "Skriware_Functions.h"

void gcode_M57();
void gcode_M58();
void gcode_M59();
void gcode_M60();
void gcode_M61();
void gcode_M62();
void gcode_M63();
void gcode_M64();
void gcode_M65();
void gcode_M66();
void gcode_M67();
void gcode_M68();
void gcode_M69();
void gcode_M70();
void gcode_M71();
void gcode_M72();
void gcode_M73();
void gcode_M74();
void gcode_M75();
void gcode_M76();
void gcode_M77();
void gcode_M78();
void gcode_M79();
void gcode_M80();